version: '3.4'

services:
  
  userdb: 
    image: mongo

  researchdb:
    image: mongo

  userdbviewer:
    image: mongo-express

  researchdbviewer:
    image: mongo-express
  
  userapi:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: src/User/UserAPI/Dockerfile

  researchapi:
    image: ${DOCKER_REGISTRY-}researchapi
    build:
      context: .
      dockerfile: src/Research/ResearchAPI/Dockerfile


  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: src/Gateway/ApiGateway/Dockerfile

